import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import { CartContextProvider } from "@/context/CartProvider";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by Daichi Koyanagi",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="font-bold text-lg">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <AuthProvider>
          <CartContextProvider>
            <Header />
            {children}
            <Footer />
            <Toaster position="top-right" />
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
